name: Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  Windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install GDAL & GEOS
        run: |
          Invoke-WebRequest http://download.osgeo.org/osgeo4w/osgeo4w-setup-x86_64.exe -OutFile osgeo4w-setup-x86_64.exe
          .\osgeo4w-setup-x86_64.exe -q -A -S -k -a x86_64 -R C:\Software -s http://download.osgeo.org/osgeo4w/ -P gdal geos
          dir C:\Software\
          
#      - name: Install GDAL
#        run: |
#          echo $env:VCPKG_INSTALLATION_ROOT
#          $env:VCPKG_DEFAULT_TRIPLET="x64-windows"
#          vcpkg install gdal geos
      - name: Install Geoflow
        run: |
          Invoke-WebRequest https://github.com/geoflow3d/geoflow/releases/download/v0.1.2/Geoflow-0.1.2-win64.exe -OutFile geoflow-setup.exe
          .\geoflow-setup.exe /S
#      - name: Build
#        run: |
#          mkdir build
#          cd build
#          cmake .. -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -DCMAKE_INSTALL_PREFIX=C:\Software -DGEOS_LIBRARY=C:/vcpkg/installed/x64-windows/lib/geos_c.lib
#          cmake --build . --target gfp_gdal --parallel 4 --config Release
      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=C:\Software -DGDAL_INCLUDE_DIR=C:\Software\include -DGDAL_LIBRARY=C:\Software\lib\gdal_i.lib -DGEOS_LIBRARY=C:\Software\lib\geos_c.lib
          cmake --build . --target gfp_gdal --parallel 4 --config Release
      - name: Create artifact
        uses: actions/upload-artifact@master
        with:
          name: gfp_gdal-win64
          path: build/Release/gfp_gdal.dll
