name: Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  Windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install GDAL
        run: |
          Invoke-WebRequest http://download.gisinternals.com/sdk/downloads/release-1911-x64-gdal-2-4-4-mapserver-7-4-3-libs.zip -OutFile release-1911-x64-gdal-2-4-4-mapserver-7-4-3-libs.zip
          mkdir C:\Software\GDAL\
          unzip release-1911-x64-gdal-2-4-4-mapserver-7-4-3-libs.zip -d C:\Software\GDAL
      - name: Install Geoflow
        run: |
          Invoke-WebRequest https://github.com/geoflow3d/geoflow/releases/download/v0.1.2/Geoflow-0.1.2-win64.exe -OutFile geoflow-setup.exe
          .\geoflow-setup.exe /S
      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=C:\Software -DGDAL_INCLUDE_DIR=C:\Software\GDAL\include -DGDAL_LIBRARY=C:\Software\GDAL\lib\gdal_i.lib -DGEOS_LIBRARY=C:\Software\GDAL\lib\geos_c.lib
          cmake --build . --target gfp_gdal --parallel 4 --config Release
      - name: Create artifact
        uses: actions/upload-artifact@master
        with:
          name: gfp_gdal-win64
          path: build/Release/gfp_gdal.dll
